"""SMTP wrapper for sending manufacturer-MI inquiry emails.

Configure via env vars (set in backend/.env and on Render):
    SMTP_HOST       e.g. smtp.gmail.com
    SMTP_PORT       587 (STARTTLS) or 465 (SSL) — defaults to 587
    SMTP_USERNAME   the gmail/account address used to authenticate
    SMTP_PASSWORD   Gmail App Password (NOT the regular gmail password)
    SMTP_FROM       optional display "Name <addr@host>"; defaults to SMTP_USERNAME
"""
from __future__ import annotations

import os
import smtplib
import ssl
from dataclasses import dataclass
from email.message import EmailMessage
from email.utils import formataddr, make_msgid
from typing import Optional


class EmailConfigError(RuntimeError):
    """Raised when SMTP env vars are missing or invalid."""


@dataclass
class SmtpConfig:
    host: str
    port: int
    username: str
    password: str
    from_addr: str

    @classmethod
    def from_env(cls) -> "SmtpConfig":
        host = os.getenv("SMTP_HOST")
        username = os.getenv("SMTP_USERNAME")
        password = os.getenv("SMTP_PASSWORD")
        if not host or not username or not password:
            missing = [k for k, v in {
                "SMTP_HOST": host,
                "SMTP_USERNAME": username,
                "SMTP_PASSWORD": password,
            }.items() if not v]
            raise EmailConfigError(
                f"SMTP not configured. Missing env var(s): {', '.join(missing)}. "
                "Add them to backend/.env."
            )
        try:
            port = int(os.getenv("SMTP_PORT", "587"))
        except ValueError as e:
            raise EmailConfigError(f"SMTP_PORT must be an integer: {e}")
        from_addr = os.getenv("SMTP_FROM") or username
        return cls(host=host, port=port, username=username, password=password, from_addr=from_addr)


def _build_message(
    *,
    cfg: SmtpConfig,
    inquiry_id: int,
    manufacturer_name: str,
    to_email: str,
    subject: str,
    question: str,
    requester_name: Optional[str],
    requester_email: Optional[str],
) -> EmailMessage:
    msg = EmailMessage()

    # Tag the subject so we can match replies back to this inquiry
    msg["Subject"] = f"[InpharmD #{inquiry_id}] {subject}"
    msg["From"] = cfg.from_addr
    msg["To"] = to_email
    # If a requester email is provided, route replies there; otherwise to our sender
    reply_to = requester_email or cfg.username
    msg["Reply-To"] = formataddr((requester_name, reply_to)) if requester_name else reply_to
    msg["Message-ID"] = make_msgid(domain=cfg.host)

    requester_line = ""
    if requester_name and requester_email:
        requester_line = f"\nRequested by: {requester_name} <{requester_email}>\n"
    elif requester_email:
        requester_line = f"\nRequested by: {requester_email}\n"
    elif requester_name:
        requester_line = f"\nRequested by: {requester_name}\n"

    body = f"""\
Hello,

This is a medical-information inquiry from InpharmD on behalf of a pharmacist
seeking clinical information about {manufacturer_name}.

QUESTION:
{question}

We would appreciate your written response at your earliest convenience.
{requester_line}
To help us route your reply, please keep the subject line intact
(it contains the inquiry reference [InpharmD #{inquiry_id}]).

Thank you for your time,
InpharmD Medical Information Team

—
This message was generated by the InpharmD inquiry system.
If this email reached you in error, please disregard.
"""
    msg.set_content(body)
    return msg


def send_inquiry_email(
    *,
    inquiry_id: int,
    manufacturer_name: str,
    to_email: str,
    subject: str,
    question: str,
    requester_name: Optional[str] = None,
    requester_email: Optional[str] = None,
) -> str:
    """Send the inquiry email via SMTP. Returns the Message-ID on success."""
    cfg = SmtpConfig.from_env()
    msg = _build_message(
        cfg=cfg,
        inquiry_id=inquiry_id,
        manufacturer_name=manufacturer_name,
        to_email=to_email,
        subject=subject,
        question=question,
        requester_name=requester_name,
        requester_email=requester_email,
    )

    context = ssl.create_default_context()
    if cfg.port == 465:
        # Implicit SSL
        with smtplib.SMTP_SSL(cfg.host, cfg.port, context=context, timeout=20) as server:
            server.login(cfg.username, cfg.password)
            server.send_message(msg)
    else:
        # STARTTLS (port 587 and friends)
        with smtplib.SMTP(cfg.host, cfg.port, timeout=20) as server:
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            server.login(cfg.username, cfg.password)
            server.send_message(msg)

    return msg["Message-ID"]
