"""SendGrid wrapper for sending manufacturer-MI inquiry emails.

Sends are made through the SendGrid v3 Web API (no SMTP). Replies come back to
the same mailbox (EMAIL_FROM) and are picked up by `imap_service.py`.

Configure via env vars (set in backend/.env and on Render):
    SENDGRID_API_KEY   your SendGrid API key (starts with "SG.")
    EMAIL_FROM         the constant From address, e.g. druginfo@inpharmd.com
    EMAIL_FROM_NAME    optional display name; defaults to "InpharmD Medical Information"
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from typing import Optional

import httpx

log = logging.getLogger("inquiry.email")

SENDGRID_SEND_URL = "https://api.sendgrid.com/v3/mail/send"
DEFAULT_FROM = "druginfo@inpharmd.com"
DEFAULT_FROM_NAME = "InpharmD Medical Information"


class EmailConfigError(RuntimeError):
    """Raised when SendGrid env vars are missing or invalid."""


@dataclass
class SendGridConfig:
    api_key: str
    from_addr: str
    from_name: str

    @classmethod
    def from_env(cls) -> "SendGridConfig":
        api_key = os.getenv("SENDGRID_API_KEY")
        if not api_key:
            raise EmailConfigError(
                "SendGrid not configured. Missing env var SENDGRID_API_KEY. "
                "Add it to backend/.env."
            )
        from_addr = os.getenv("EMAIL_FROM") or DEFAULT_FROM
        from_name = os.getenv("EMAIL_FROM_NAME") or DEFAULT_FROM_NAME
        return cls(api_key=api_key, from_addr=from_addr, from_name=from_name)


def _build_body(
    *,
    inquiry_id: int,
    manufacturer_name: str,
    question: str,
    requester_name: Optional[str],
    requester_email: Optional[str],
    medication_name: Optional[str] = None,
    pi_storage_data: Optional[str] = None,
    pi_link: Optional[str] = None,
) -> str:
    requester_line = ""
    if requester_name and requester_email:
        requester_line = f"\nRequested by: {requester_name} <{requester_email}>\n"
    elif requester_email:
        requester_line = f"\nRequested by: {requester_email}\n"
    elif requester_name:
        requester_line = f"\nRequested by: {requester_name}\n"

    product_section = ""
    if medication_name or pi_storage_data or pi_link:
        lines = ["PRODUCT DETAILS:"]
        if medication_name:
            lines.append(f"Medication/Vaccine: {medication_name}")
        if pi_storage_data:
            lines.append(f"PI Storage Information: {pi_storage_data}")
        if pi_link:
            lines.append(f"Prescribing Information: {pi_link}")
        product_section = "\n" + "\n".join(lines) + "\n"

    return f"""\
Hello,

This is a medical-information inquiry from InpharmD on behalf of a pharmacist
seeking clinical information about {manufacturer_name}.

QUESTION:
{question}
{product_section}
We would appreciate your written response at your earliest convenience.
{requester_line}
To help us route your reply, please keep the subject line intact
(it contains the inquiry reference [InpharmD #{inquiry_id}]).

Thank you for your time,
InpharmD Medical Information Team

—
This message was generated by the InpharmD inquiry system.
If this email reached you in error, please disregard.
"""


def send_inquiry_email(
    *,
    inquiry_id: int,
    manufacturer_name: str,
    to_email: str,
    subject: str,
    question: str,
    requester_name: Optional[str] = None,
    requester_email: Optional[str] = None,
    medication_name: Optional[str] = None,
    pi_storage_data: Optional[str] = None,
    pi_link: Optional[str] = None,
) -> str:
    """Send the inquiry email via the SendGrid API.

    Returns SendGrid's X-Message-Id header (used to correlate replies / events).
    Replies are routed back to EMAIL_FROM so IMAP polling can capture them.
    """
    cfg = SendGridConfig.from_env()

    tagged_subject = f"[InpharmD #{inquiry_id}] {subject}"
    body = _build_body(
        inquiry_id=inquiry_id,
        manufacturer_name=manufacturer_name,
        question=question,
        requester_name=requester_name,
        requester_email=requester_email,
        medication_name=medication_name,
        pi_storage_data=pi_storage_data,
        pi_link=pi_link,
    )

    payload = {
        "personalizations": [{"to": [{"email": to_email}]}],
        "from": {"email": cfg.from_addr, "name": cfg.from_name},
        # Replies must land in our mailbox so imap_service can read them.
        "reply_to": {"email": cfg.from_addr, "name": cfg.from_name},
        "subject": tagged_subject,
        "content": [{"type": "text/plain", "value": body}],
    }

    headers = {
        "Authorization": f"Bearer {cfg.api_key}",
        "Content-Type": "application/json",
    }

    with httpx.Client(timeout=30) as client:
        resp = client.post(SENDGRID_SEND_URL, headers=headers, json=payload)
        if resp.status_code >= 400:
            raise RuntimeError(
                f"SendGrid rejected the send: {resp.status_code} {resp.text}"
            )
        message_id = resp.headers.get("X-Message-Id") or ""

    log.info("Sent inquiry %s to %s via SendGrid (msg id %s)", inquiry_id, to_email, message_id)
    return message_id
